version: '3.9'

services:

  db:
    image: postgis/postgis:14-3.3
    container_name: ecommerce_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: senfidel/projetsvde:backendboutique-latest
    build:
      context: ./${BACKEND_DIR}
    container_name: ecommerce_backend
    env_file: ./backendboutique/EBoutique_API/.env
    
    depends_on:
      - db
    ports:
      - "8000:5000"
    command: ./entrypoint.sh

  frontend:
    image: senfidel/projetsvde:frontendboutique-latest
    build:
      context: ./${FRONTEND_DIR}
    container_name: ecommerce_frontend
    depends_on:
      - backend
    ports:
      - "3000:5001"

volumes:
  postgres_data:
